// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbuiabcfvonvggazkzvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxidWlhYmNmdm9udmdnYXprenZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNTE0ODksImV4cCI6MjA3NjcyNzQ4OX0.K6LWe0520xxQwrYujXdjeLfAwtE9_X6O58viD7u--J8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});